- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
  - innotop
  - ipython
  - ipython/profile_default
  - ipython/profile_default/startup
  - config
  - config/git
  - config/pip
  tags:
  - dotfiles

- name: dotfiles links
  file:
    src: '{{ ansible_env.PWD }}/roles/adam_mac/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
  - ansible.cfg
  - config/karabiner
  - config/starship.toml
  - config/git/attributes
  - config/git/config
  - config/git/ignore
  - config/pip/pip.conf
  - digrc
  - inputrc
  - ipython/profile_default/startup/00-imports.py
  - ssh/config
  - zprofile
  - zshrc
  tags:
  - dotfiles

- name: innotop.conf
  copy:
    src: dotfiles/innotop/innotop.conf
    dest: ~/.innotop/innotop.conf
    force: false  # Only if it doesn't exist
